import ScrollContainer from "./components/layout/scroll-container";
import localFont from "next/font/local";
import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import Header from "@/app/components/layout/header";
import Banner from "@/app/components/layout/banner";
import Footer from "@/app/components/layout/footer";

import "@/app/styles/globals.scss";

const pretendard = localFont({
    src: "./styles/fonts/PretendardVariable.woff2",
    display: "swap",
    weight: "45 920",
    variable: "--font-pretendard",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko">
            <body className={`${GeistSans.variable} ${pretendard.variable}`}>
                <div className="wrap">
                    <Header />
                    <div className="container">
                        <ScrollContainer>{children}</ScrollContainer>
                    </div>
                    <Banner />
                    <Footer />
                </div>
            </body>
        </html>
    );
}
